/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,ts}'],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.1em' }],
      },
      colors: {
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'surface-variant': '#2d3449',
        surface: '#0b1326',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#b9cacb',
        'on-primary': '#00363a',
        'on-primary-container': '#006970',
        primary: '#dbfcff',
        'primary-container': '#00f0ff',
        'inverse-primary': '#006970',
        secondary: '#c0c1ff',
        'on-secondary': '#1000a9',
        'on-secondary-container': '#b0b2ff',
        'secondary-container': '#3131c0',
        'secondary-fixed': '#e1e0ff',
        'secondary-fixed-dim': '#c0c1ff',
        outline: '#849495',
        'outline-variant': '#3b494b',
        tertiary: '#fdf2ff',
        'on-tertiary': '#490080',
        'tertiary-container': '#eacfff',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
      },
      boxShadow: {
        nav: '0 4px 20px rgba(0, 0, 0, 0.05)',
        'nav-dark': '0 20px 40px rgba(0, 0, 0, 0.4)',
        cta: '0 12px 28px rgba(0, 240, 255, 0.18)',
        'cta-light': '0 12px 28px rgba(0, 240, 255, 0.12)',
        hero: '0 20px 40px rgba(0, 240, 255, 0.18)',
        'hero-light': '0 20px 40px rgba(0, 240, 255, 0.12)',
      },
    },
  },
  plugins: [],
};
